### ISSUE TITLE
Cube CSS

### ISSUE THREAD

**Issue by masakudamatsu** [masakudamatsu/masakudamatsu.github.io#6]
## Design tokens

For color, font size scale, and whitespace scale, use CSS variables at `:root` selector
```css
:root {
  /* Major Third scale */
  --base-size: 1rem;
  --scale: 1.25;
  --size300: calc(var(--base-size) / var(--scale));
  --size400: var(--base-size);
  --size500: calc(var(--base-size) * var(--scale));
  --size600: calc(var(--size500) * var(--scale));
  --size700: calc(var(--size600) * var(--scale));
  /* Color scheme */
  --primary: #231651;
  --secondary: #ff8484;
  --secondary-shade: #ff5151;
  --tertiary: #2c988c;
  --tertiary-glare: #d6fff6;
  --light: #fafafa;
  --grey: #c4c4c4;  
}
```

or go fancy with font-size specification
```css
p {
    /* font metrics */
    --font: Catamaran;
    --fm-capitalHeight: 0.68;
    --fm-descender: 0.54;
    --fm-ascender: 1.1;
    --fm-linegap: 0;

    /* desired font-size for capital height */
    --capital-height: 100;

    /* apply font-family */
    font-family: var(--font);

    /* compute font-size to get capital height equal desired font-size */
    --computedFontSize: (var(--capital-height) / var(--fm-capitalHeight));
    font-size: calc(var(--computedFontSize) * 1px);
}
```
source: https://iamvdo.me/en/blog/css-font-metrics-line-height-and-vertical-align

## Global style
Start with element selectors to typeset each element (`body`, `h1`, `h2`, `h3`, `a`).

Also any style for `body` element (e.g., whitespace at the bottom)

Define focus style:
```css
:focus {
  outline: 2px dotted;
  outline-offset: 0.25rem;
}
```

### Shape
```css
.round-rect {
  border-radius: 0.5rem;
}
```
### Texture
```css
.bg-primary {
  background: var(--primary);
}
```
### Font
Create a class to specify a particular typeface (including its weight)
```css
.font-base {
  font-family: "IBM Plex Sans", Helvetica, Arial, sans-serif';
  font-weight: 500;
}
.font-bold {
  font-family: "IBM Plex Sans", Helvetica, Arial, sans-serif';
  font-weight: 700;
}
.font-mono {
  font-family: '"IBM Plex Mono", Courier New, Courier, monospace';
  font-weight: 500;
}
```
Create separate classes for font-size and color
```css
.color-primary {
  color: var(--primary);
}
.color-secondary {
  color: var(--secondary);
}
.text-400 {
  font-size: var(--size400);
}
.text-600 {
  font-size: var(--size600);
}
.text-700 {
  font-size: var(--size700);
}
```
### Spacing
```css
v.gap-top-600 {
  margin-top: var(--size600);
}
.gap-top-700 {
  margin-top: var(--size700);
}
```
### Visually-hidden
```css
.visually-hidden {
  border: 0;
  clip: rect(0 0 0 0);
  height: auto;
  margin: 0;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
  white-space: nowrap;
}
```

## Composition
If the same pattern of layout repeats, make it a utility:
### Center-alignment
```css
.wrapper {
  max-width: 75rem;
  margin-left: auto;
  margin-right: auto;
  padding: 0 var(--size500);
}
```
### Vertical-spacing
```css
.flow > * + * {
  margin-top: var(--flow-space, 1rem);
}
```
### Responsive two-column layout
```css
.splitter > :lastchild {
  margin-top: var(--size500);
}
@media (min-width: 48em) {
  .splitter {
    display: flex;
  }
  .splitter > * {
    flex-grow: 1;
  }
  .splitter > :lastchild {
    margin-top: 0;
    margin-left: var(--size500);
    min-width: 22rem;
  }
}

## Blocks
### One-off layout
For one-off layout, make it as a "block" similar to the common notion of a "component"
```css
.site-head {
  padding: 0.8rem 0;
}
.site-head__inner {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: space-between;
}
.site-head h1 {
  margin: 0.5rem 1rem 0.5rem 0;
}
```

### Standard UI elements
UI elements like buttons, create a block:
```css
.button {
  font: inherit;
  display: inline-block;
  line-height: 1;
  text-decoration: none;
  border: 1px solid var(--secondary);
  background: var(--secondary);
  padding: 0.6rem 1.5rem;
  position: relative;
}
.button:focus {
  outline-offset: -0.4rem;
  outline: 1px solid;
}

.button:hover {
  background: var(--primary);
  border-color: var(--primary);
  color: var(--light);
}
.button:active {
  transform: scale(0.95);
}

```

## Exceptions
A version of block should be created with a data attribute:
```css
.button[data-variant='ghost'] {
  border-color: currentColor;
  background: transparent;
}
```
> Because the exception is often caused by outside influence, such as JavaScript, a mechanism that both CSS and JavaScript can use efficiently makes sense, too. It’s also useful to consider exceptions in the context of a [finite state machine (opens new window)](https://github.com/davidkpiano/xstate) too. — [Cube CSS Doc](https://cube.fyi/exception.html#why-data-attributes)
